=begin
#finAPI RESTful Services (alpha build)

#finAPI RESTful Services (alpha build)

OpenAPI spec version: finAPI PSD2-alpha (based on v.1.73.0)

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'date'

module FinapiApiClient
  # Client configuration parameters
  class ClientConfigurationParams
    # Callback URL to which finAPI sends the notification messages that are triggered from the automatic batch update of the users' bank connections. This field is only relevant if the automatic batch update is enabled for your client. For details about what the notification messages look like, please see the documentation in the 'Notification Rules' section. finAPI will call this URL with HTTP method POST. Note that the response of the call is not processed by finAPI. Also note that while the callback URL may be a non-secured (http) URL on the finAPI sandbox or alpha environment, it MUST be a SSL-secured (https) URL on the finAPI live system.<p>The maximum allowed length of the URL is 512. If you have previously set a callback URL and now want to clear it (thus disabling user-related notifications altogether), you can pass an empty string (\"\").
    attr_accessor :user_notification_callback_url

    # Callback URL for user synchronization. This field should be set if you - as a finAPI customer - have multiple clients using finAPI. In such case, all of your clients will share the same user base, making it possible for a user to be created in one client, but then deleted in another. To keep the client-side user data consistent in all clients, you should set a callback URL for each client. finAPI will send a notification to the callback URL of each client whenever a user of your user base gets deleted. Note that finAPI will send a deletion notification to ALL clients, including the one that made the user deletion request to finAPI. So when deleting a user in finAPI, a client should rely on the callback to delete the user on its own side. <p>The notification that finAPI sends to the clients' callback URLs will be a POST request, with this body: <pre>{    \"userId\" : string // contains the identifier of the deleted user    \"event\" : string // this will always be \"DELETED\" }</pre><br/>Note that finAPI does not process the response of this call. Also note that while the callback URL may be a non-secured (http) URL on the finAPI sandbox or alpha system, it MUST be a SSL-secured (https) URL on the live system.</p>As long as you have just one client, you can ignore this field and let it be null. However keep in mind that in this case your client will not receive any callback when a user gets deleted - so the deletion of the user on the client-side must not be forgotten. Of course you may still use the callback URL even for just one client, if you want to implement the deletion of the user on the client-side via the callback from finAPI.<p> The maximum allowed length of the URL is 512. If you have previously set a callback URL and now want to clear it (thus disabling user synchronization related notifications for this client), you can pass an empty string (\"\").
    attr_accessor :user_synchronization_callback_url

    # The validity period that newly requested refresh tokens initially have (in seconds). The value must be greater than or equal to 60, or 0. A value of 0 means that the tokens never expire (Unless explicitly invalidated, e.g. by revocation , or when a user gets locked, or when the password is reset for a user).
    attr_accessor :refresh_tokens_validity_period

    # The validity period that newly requested access tokens for users initially have (in seconds). The value must be greater than or equal to 60, or 0. A value of 0 means that the tokens never expire.
    attr_accessor :user_access_tokens_validity_period

    # The validity period that newly requested access tokens for clients initially have (in seconds). The value must be greater than or equal to 60, or 0. A value of 0 means that the tokens never expire.
    attr_accessor :client_access_tokens_validity_period

    # Whether <a href='https://finapi.zendesk.com/hc/en-us/articles/360002596391' target='_blank'>finAPI's web form</a> should provide a checkbox for the user allowing him to choose whether to store his banking PIN in finAPI. If this field is set to false, then the user won't have an option to store his PIN.<br><br>NOTE: This field is deprecated and will be removed at some point. Use 'storeSecretsAvailableInWebForm' instead.
    attr_accessor :is_pin_storage_available_in_web_form

    # Whether <a href='https://finapi.zendesk.com/hc/en-us/articles/360002596391' target='_blank'>finAPI's web form</a> will provide a checkbox for the user allowing him to choose whether to store login secrets (like a PIN, or a token from the bank) in finAPI. If this field is set to false, then the user won't have an option to store this data.
    attr_accessor :store_secrets_available_in_web_form

    # When an application name is set (e.g. \"My App\"), then <a href='https://finapi.zendesk.com/hc/en-us/articles/360002596391' target='_blank'>finAPI's web form</a> will display a text to the user \"Weiterleitung auf finAPI von ...\" (e.g. \"Weiterleitung auf finAPI von My App\"). If you have previously set a application name and now want to clear it, you can pass an empty string (\"\"). Maximum length: 64
    attr_accessor :application_name

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'user_notification_callback_url' => :'userNotificationCallbackUrl',
        :'user_synchronization_callback_url' => :'userSynchronizationCallbackUrl',
        :'refresh_tokens_validity_period' => :'refreshTokensValidityPeriod',
        :'user_access_tokens_validity_period' => :'userAccessTokensValidityPeriod',
        :'client_access_tokens_validity_period' => :'clientAccessTokensValidityPeriod',
        :'is_pin_storage_available_in_web_form' => :'isPinStorageAvailableInWebForm',
        :'store_secrets_available_in_web_form' => :'storeSecretsAvailableInWebForm',
        :'application_name' => :'applicationName'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'user_notification_callback_url' => :'String',
        :'user_synchronization_callback_url' => :'String',
        :'refresh_tokens_validity_period' => :'Integer',
        :'user_access_tokens_validity_period' => :'Integer',
        :'client_access_tokens_validity_period' => :'Integer',
        :'is_pin_storage_available_in_web_form' => :'BOOLEAN',
        :'store_secrets_available_in_web_form' => :'BOOLEAN',
        :'application_name' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'userNotificationCallbackUrl')
        self.user_notification_callback_url = attributes[:'userNotificationCallbackUrl']
      end

      if attributes.has_key?(:'userSynchronizationCallbackUrl')
        self.user_synchronization_callback_url = attributes[:'userSynchronizationCallbackUrl']
      end

      if attributes.has_key?(:'refreshTokensValidityPeriod')
        self.refresh_tokens_validity_period = attributes[:'refreshTokensValidityPeriod']
      end

      if attributes.has_key?(:'userAccessTokensValidityPeriod')
        self.user_access_tokens_validity_period = attributes[:'userAccessTokensValidityPeriod']
      end

      if attributes.has_key?(:'clientAccessTokensValidityPeriod')
        self.client_access_tokens_validity_period = attributes[:'clientAccessTokensValidityPeriod']
      end

      if attributes.has_key?(:'isPinStorageAvailableInWebForm')
        self.is_pin_storage_available_in_web_form = attributes[:'isPinStorageAvailableInWebForm']
      end

      if attributes.has_key?(:'storeSecretsAvailableInWebForm')
        self.store_secrets_available_in_web_form = attributes[:'storeSecretsAvailableInWebForm']
      end

      if attributes.has_key?(:'applicationName')
        self.application_name = attributes[:'applicationName']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          user_notification_callback_url == o.user_notification_callback_url &&
          user_synchronization_callback_url == o.user_synchronization_callback_url &&
          refresh_tokens_validity_period == o.refresh_tokens_validity_period &&
          user_access_tokens_validity_period == o.user_access_tokens_validity_period &&
          client_access_tokens_validity_period == o.client_access_tokens_validity_period &&
          is_pin_storage_available_in_web_form == o.is_pin_storage_available_in_web_form &&
          store_secrets_available_in_web_form == o.store_secrets_available_in_web_form &&
          application_name == o.application_name
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [user_notification_callback_url, user_synchronization_callback_url, refresh_tokens_validity_period, user_access_tokens_validity_period, client_access_tokens_validity_period, is_pin_storage_available_in_web_form, store_secrets_available_in_web_form, application_name].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = FinapiApiClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
