=begin
#finAPI RESTful Services (alpha build)

#finAPI RESTful Services (alpha build)

OpenAPI spec version: finAPI PSD2-alpha (based on v.1.73.0)

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FinapiApi::AccountInterface
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AccountInterface' do
  before do
    # run before each test
    @instance = FinapiApi::AccountInterface.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountInterface' do
    it 'should create an instance of AccountInterface' do
      expect(@instance).to be_instance_of(FinapiApi::AccountInterface)
    end
  end
  describe 'test attribute "capabilities"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["DATA_DOWNLOAD", "IBAN_ONLY_SEPA_MONEY_TRANSFER", "IBAN_ONLY_SEPA_DIRECT_DEBIT", "SEPA_MONEY_TRANSFER", "SEPA_COLLECTIVE_MONEY_TRANSFER", "SEPA_BASIC_DIRECT_DEBIT", "SEPA_BASIC_COLLECTIVE_DIRECT_DEBIT", "SEPA_B2B_DIRECT_DEBIT", "SEPA_B2B_COLLECTIVE_DIRECT_DEBIT"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.capabilities = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "last_successful_update"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "last_update_attempt"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["UPDATED", "UPDATED_FIXED", "DOWNLOAD_IN_PROGRESS", "DOWNLOAD_FAILED", "DEPRECATED"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "interface"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
