=begin
#finAPI RESTful Services (alpha build)

#finAPI RESTful Services (alpha build)

OpenAPI spec version: finAPI PSD2-alpha (based on v.1.73.0)

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

# Common files
require 'finapi_api_client/api_client'
require 'finapi_api_client/api_error'
require 'finapi_api_client/version'
require 'finapi_api_client/configuration'

# Models
require 'finapi_api_client/models/access_token'
require 'finapi_api_client/models/account'
require 'finapi_api_client/models/account_interface'
require 'finapi_api_client/models/account_list'
require 'finapi_api_client/models/account_params'
require 'finapi_api_client/models/bad_credentials_error'
require 'finapi_api_client/models/bank'
require 'finapi_api_client/models/bank_connection'
require 'finapi_api_client/models/bank_connection_interface'
require 'finapi_api_client/models/bank_connection_list'
require 'finapi_api_client/models/bank_connection_owner'
require 'finapi_api_client/models/bank_consent'
require 'finapi_api_client/models/bank_interface'
require 'finapi_api_client/models/bank_interface_login_field'
require 'finapi_api_client/models/bank_list'
require 'finapi_api_client/models/cash_flow'
require 'finapi_api_client/models/cash_flow_list'
require 'finapi_api_client/models/categorization_check_result'
require 'finapi_api_client/models/categorization_check_results'
require 'finapi_api_client/models/category'
require 'finapi_api_client/models/category_list'
require 'finapi_api_client/models/category_params'
require 'finapi_api_client/models/change_client_credentials_params'
require 'finapi_api_client/models/check_categorization_data'
require 'finapi_api_client/models/check_categorization_transaction_data'
require 'finapi_api_client/models/clearing_account_data'
require 'finapi_api_client/models/client_configuration'
require 'finapi_api_client/models/client_configuration_params'
require 'finapi_api_client/models/connect_interface_params'
require 'finapi_api_client/models/daily_balance'
require 'finapi_api_client/models/daily_balance_list'
require 'finapi_api_client/models/direct_debit_ordering_response'
require 'finapi_api_client/models/edit_bank_connection_params'
require 'finapi_api_client/models/edit_category_params'
require 'finapi_api_client/models/error_details'
require 'finapi_api_client/models/error_message'
require 'finapi_api_client/models/execute_password_change_params'
require 'finapi_api_client/models/execute_sepa_direct_debit_params'
require 'finapi_api_client/models/execute_sepa_money_transfer_params'
require 'finapi_api_client/models/iban_rule'
require 'finapi_api_client/models/iban_rule_list'
require 'finapi_api_client/models/iban_rule_params'
require 'finapi_api_client/models/iban_rules_params'
require 'finapi_api_client/models/identifier_list'
require 'finapi_api_client/models/identifiers_params'
require 'finapi_api_client/models/import_bank_connection_params'
require 'finapi_api_client/models/keyword_rule'
require 'finapi_api_client/models/keyword_rule_list'
require 'finapi_api_client/models/keyword_rule_params'
require 'finapi_api_client/models/keyword_rules_params'
require 'finapi_api_client/models/label'
require 'finapi_api_client/models/label_list'
require 'finapi_api_client/models/label_params'
require 'finapi_api_client/models/login_credential_data'
require 'finapi_api_client/models/login_credential_resource'
require 'finapi_api_client/models/mock_account_data'
require 'finapi_api_client/models/mock_bank_connection_update'
require 'finapi_api_client/models/mock_batch_update_params'
require 'finapi_api_client/models/money_transfer_ordering_response'
require 'finapi_api_client/models/monthly_user_stats'
require 'finapi_api_client/models/multi_step_authentication'
require 'finapi_api_client/models/new_transaction'
require 'finapi_api_client/models/notification_rule'
require 'finapi_api_client/models/notification_rule_list'
require 'finapi_api_client/models/notification_rule_params'
require 'finapi_api_client/models/pageable_bank_list'
require 'finapi_api_client/models/pageable_category_list'
require 'finapi_api_client/models/pageable_iban_rule_list'
require 'finapi_api_client/models/pageable_keyword_rule_list'
require 'finapi_api_client/models/pageable_label_list'
require 'finapi_api_client/models/pageable_payment_resources'
require 'finapi_api_client/models/pageable_security_list'
require 'finapi_api_client/models/pageable_transaction_list'
require 'finapi_api_client/models/pageable_user_info_list'
require 'finapi_api_client/models/paging'
require 'finapi_api_client/models/password_changing_resource'
require 'finapi_api_client/models/payment'
require 'finapi_api_client/models/payment_execution_response'
require 'finapi_api_client/models/paypal_transaction_data'
require 'finapi_api_client/models/remove_interface_params'
require 'finapi_api_client/models/request_password_change_params'
require 'finapi_api_client/models/request_sepa_direct_debit_params'
require 'finapi_api_client/models/request_sepa_money_transfer_params'
require 'finapi_api_client/models/security'
require 'finapi_api_client/models/security_list'
require 'finapi_api_client/models/single_direct_debit_data'
require 'finapi_api_client/models/single_money_transfer_recipient_data'
require 'finapi_api_client/models/split_transactions_params'
require 'finapi_api_client/models/sub_transaction_params'
require 'finapi_api_client/models/train_categorization_data'
require 'finapi_api_client/models/train_categorization_transaction_data'
require 'finapi_api_client/models/transaction'
require 'finapi_api_client/models/transaction_list'
require 'finapi_api_client/models/trigger_categorization_params'
require 'finapi_api_client/models/two_step_procedure'
require 'finapi_api_client/models/update_bank_connection_params'
require 'finapi_api_client/models/update_multiple_transactions_params'
require 'finapi_api_client/models/update_result'
require 'finapi_api_client/models/update_transactions_params'
require 'finapi_api_client/models/user'
require 'finapi_api_client/models/user_create_params'
require 'finapi_api_client/models/user_identifiers_list'
require 'finapi_api_client/models/user_identifiers_params'
require 'finapi_api_client/models/user_info'
require 'finapi_api_client/models/user_update_params'
require 'finapi_api_client/models/verification_status_resource'
require 'finapi_api_client/models/web_form'

# APIs
require 'finapi_api_client/api/accounts_api'
require 'finapi_api_client/api/authorization_api'
require 'finapi_api_client/api/bank_connections_api'
require 'finapi_api_client/api/banks_api'
require 'finapi_api_client/api/categories_api'
require 'finapi_api_client/api/client_configuration_api'
require 'finapi_api_client/api/labels_api'
require 'finapi_api_client/api/mandator_administration_api'
require 'finapi_api_client/api/mocks_and_tests_api'
require 'finapi_api_client/api/notification_rules_api'
require 'finapi_api_client/api/payments_api'
require 'finapi_api_client/api/securities_api'
require 'finapi_api_client/api/transactions_api'
require 'finapi_api_client/api/users_api'
require 'finapi_api_client/api/web_forms_api'

module FinapiApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   FinapiApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
